* Quiz 2
** Acute Cholecystitis
  Due to the Gallbladder being blocked.
  Blockage can be caused by gallstones, this will lead to the gb being infected
  The cystic duct connects it to the ___, bile can't be drained.
*** Symptoms
   Fever
   Nausea
   RUQ pain
*** Treatment
   Antibiotics
** GERD(Acid Reflux)
  LES doesn't close properly.
  Uclers, bleeding, narrowings, intestinal cells in espohagus(Causin cancer)
*** Treatment
   IV pain meds, sedative
   Catheter in bladder
   General anesth
   Breathing tube
   Open Fundoplication
   Laparoscopic Fundoplication
** Hiatal Hernia
   Pull stomach back into place and tigthens Hernia ring to prevent it from happening

*** Acute Pancreatitis

* 3-21
** Esophageal Varices
   Dilated veins in esophageal wall
   Occur 2 to hepatic cirrhosis, common in EtOH abusers
*** Portal hypertension
    Hepatic scarring slows blood flow
    Blood backs up in portal circulation 
    Pressure rises
    Vessels in portal circulation become distended
** Aortic Aneurysm
   Localized dilation due to weakening of aortic wall
   Usually older patient with history of hypertension, atherosclerosis
   May occur in younger patients secondary to
   -Trauma
   -Marfan's syndrome
   Usually just above aortic bifurcation
   May extend to one or both iliac arteries
** Signs and Symptoms
   Unilateral lower quadrant pain; low back or leg pain
   May be described as terring or ripping
   Pulstabile palpable mass usually above umbilicus
   Diminished pulses in lower extermities
   Unexplained syncope, often after BM
   Ecidence of hypovelmic shock
** Ectopic Pregnancy
  Suspect in females of child-bearing age with:
  Abdominal pain
  Unexplained shock
  Last normal menstrual period
* 3-31
** Hearts
   Heart Diagram [http://upload.wikimedia.org/wikipedia/commons/e/e0/Heart_diagram-en.svg]
*** Systde
    Makes muscule contrradcut, causes muscule to
*** Distde
** Misc
   Need oxygen to break down glucose to make ATP
* 4-1
** Major Determinants of Disease
   Most heart disease is the result of atherosclerotic obstruction of the coronary artheries.
   Congestive heart failure is mechanical failure of the heart to eject blood delievered to it.
   Metabolic or autoimmune disease may cause heart muscle or valve damage.
   High blood press accelerates atheorosclerosis and most other cardiac disease.
   Cardiac valves are suspectibile to change.
   Abnormal embryonic development of the heart produces significant cardiac anatomic malformations.
   Abnormal heartbeat patterns (arrhythmias) can cause heart problems
** Arrhythmias
   Mechanically inefficient
    -CO decreases
   Potentially fatal
*** Caused by
    myocardialschemia
    MI
    electrolyte imbalance
    stress
    caffeine
    drugs, especially stimulants
    congenital defects in the electrical network.
